### ISSUE TITLE
Bad JWE crashes _cjose_jwe_set_cek_a256gcm

### ISSUE THREAD

**Issue by balthorium** [cisco/cjose#66]
Attempts to decrypt the JWE:
```
eyJhbGciOiJBMjU2S1ciLCJraWQiOiIzYmJhNTkxMC04MzZmLTRjOTYtYjE0My0xNWM0MTkzNTRjNDAiLCJlbmMiOiJBMjU2R0NNIn0.-rqxPUoKNyVTBumul_8dLhK2uVhPRd-l55Xw6No8Fo8wN9wreuQg_g.2ZH9Jxx8tEZ7Dzdz.v2ESxQ.wKR8Ms6EI_st6Pzz424O-w
```
Using JWK:
```
{
    "kty" : "oct",
    "k" : "7SOtIzBXT6MJHRG79G7r3FiIOlNa_tuJX00IzLeYRYY"
}
```
Results in a crash here:
https://github.com/cisco/cjose/blob/master/src/jwe.c#L385

The combined use of alg=A256KW and enc=A256GCM appears to lead to the dereferencing of an invalid pointer (the jwk pointer above has value "1")

**Comment by linuxwolf** [comment]
Thanks for the report.

> 1. the JWE has an invalid header and cJose does not catch that before processing

There does not appear to be anything wrong withe the provided JWE; it properly decrypts with other JOSE libraries using the provided key.

Also, In the future, please provide textual information (filename + line number, or code snippets) instead of images of code.  Using images makes it much more difficult to find the problem areas.

**Comment by balthorium** [comment]
Thanks for the quick response, you're correct the header is fine.  Also, I've replaced the image and with a link to the line where the failure occurs.  Issue #2 from the original post I think still applies, but I will write a unit test to confirm and post a PR with proposed fixes.
